Smogon Set Import Update
architdate/PKHeX-Plugins pull request #51
Opened 2020-09-18 03:09 UTC by soopercool101

Adds support for Level, Gender flags

Closes #50

2020-09-18 05:20 UTC, architdate commented
Can you take a look at this? `view-source:https://www.smogon.com/dex/ss/pokemon/vespiquen/` it shows `level` as 0 too. By your logic this Vespiquen would then be level 5. That isn't the case here. The level check likely has to be revised.

2020-09-18 05:26 UTC, soopercool101 commented
Dang. I will have to do a format check then which is much more difficult. Very odd.

2020-09-18 05:29 UTC, architdate commented
It's likely a format check. Just do a hardcoded LC check the same way i handle `shiny` and then pass LC as a boolean. Then we know that we have to add a level line in the set if `LC == true`

The same can probably be done by making a hardcoded check for gender = DC instead of getting the first character after = (More efficient that way). 

Can you also link me a page where the gender is not DC? Thanks :)

2020-09-18 05:33 UTC, soopercool101 commented
> Can you also link me a page where the gender is not DC? 
I honestly couldn't find one myself, but I also couldn't find one where shiny=true so I figured it would be god for completion's sake.

> hardcoded check for gender = DC
Yeah that's a much better idea for sure

2020-09-18 05:34 UTC, architdate commented
Okay, then maybe lets leave the gender check out for now since we have no idea on it. Even in case of locked genders, alm will automatically gender assign properly so there isnt any need for it. :)

2020-09-18 06:01 UTC, soopercool101 commented
Tested with https://www.smogon.com/dex/dp/pokemon/clamperl which has both a UU and LC set. The LC set properly imports as level 5 and the UU set properly imports as level 100, despite both being listed as level 0

2020-09-18 06:36 UTC, soopercool101 commented
^ Last update for now. Let me know if anything else needs changing. I also gave maintainer access so if you need to make any minor adjustments feel free

2020-09-18 16:32 UTC, architdate requested changes

2020-09-18 16:32 UTC, architdate commented on PKHeX.Core.AutoMod/Teams/SmogonSetList.cs
> +
Lets just remove the gender check for now since we dont have gender specific pokemon and ALM handles single gendered mons anyway!

2020-09-18 16:32 UTC, architdate commented on PKHeX.Core.AutoMod/Teams/SmogonSetList.cs
> +                }
Your level check here is wrong actually. Take this scenario. Lets say there are 3 sets within LC. The format isnt specified for each set but its specified as one of the keys in the json. So basically we have to look back till we find the first instance of the `format` key prior to the current split.

The current implementation will only be LC for the first LC set but wont find format LC in the previous split for set 2 and set 3. I'll try and commit to your branch likely tomorrow for a fix

2020-09-18 16:39 UTC, architdate commented
My idea here is to just iterate over all splits upto i to check if any of em contain `"strategies":[{"format":`. If they do then split on it and check the second item in the list to see if it begins with LC. If it does maintain `true` in an LC variable. If another one of them is found then update the LC variable based on if the latest format is different

2020-09-18 17:18 UTC, soopercool101 commented
Updated. Tested with https://www.smogon.com/dex/xy/pokemon/pawniard/

The 3 little cup sets now correctly generate as level 5 whereas the PU and NU sets are generated as level 100. Checks for LC as the start of the format string in case LC-Uber ever catches on.

2020-09-19 01:27 UTC, architdate approved these changes

2020-09-19 01:28 UTC, architdate commented
Looks good to me! Thanks a lot for the contribution <3

2020-09-19 01:29 UTC, merged